parameters:
  - name: artifactName
    displayName: Name of the Terraform plan artifact
    type: string
  - name: environment
    displayName: Name of the environment to deploy to
    type: string
  - name: workspaceName
    displayName: Name of the Terraform workspace
    type: string
  

jobs:
  - job: plan
    displayName: Plan
    steps:
      - template: ../aws/iam/configure.yml
      - template: plan.yml
        parameters:
          artifactName: ${{ parameters.artifactName }}
          planAdditionalCommandOptions: -var-file="variables/${{ parameters.environment }}.$(AWS_DEFAULT_REGION).tfvars"
          workspaceName: ${{ parameters.workspaceName }}

  - template: ../azure-devops/approve.yml
    parameters:
      dependsOn: plan
      timeoutInMinutes: 60
      userToNotify: '[Expensely]\Expensely Team'

  - deployment: apply
    displayName: Apply
    dependsOn: approve
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - template: ../aws/iam/configure.yml
            - template: apply.yml
              parameters:
                artifactName: ${{ parameters.artifactName }}
