parameters:
  - name: dependsOn
    displayName: Name of job that needs to complete before this job
    type: string
  - name: onTimeout
    displayName: Action to take on timeout
    type: string
    default: reject
    values:
      - reject
      - resume
  - name: timeoutInMinutes
    displayName: Number of minutes until this job times out
    type: number
    default: 60
  - name: userToNotify
    displayName: Users to notify
    type: string
  - name: validationInstructions
    displayName: Validation instructions
    type: string
    default: Validate the dependant job

jobs:
  - job: approve
    displayName: Approve
    dependsOn: ${{ parameters.dependsOn }}
    pool: server
    steps:
      - task: ManualValidation@0
        displayName: Manual validation
        inputs:
          notifyUsers: ${{ parameters.userToNotify }}
          onTimeout: ${{ parameters.onTimeout }}
          instructions: ${{ parameters.validationInstructions }}
        timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
