parameters:
  - name: dockerfilePath
    displayName: Path of the dockerfile
    type: string
    default: Dockerfile
  - name: target
    displayName: Name of target to build
    type: string
  - name: tag
    displayName: Value to tag image with
    type: string
    default: $(Build.BuildNumber)
  - name: arguments
    displayName: Additional argument values
    type: string
    default: " "
  - name: workingDirectory
    displayName: Directory where the related files are located
    type: string
    default: $(Build.SourcesDirectory)

steps:
  - task: PowerShell@2
    displayName: Build ${{ parameters.target }}
    inputs:
      targetType: inline
      script: docker build -f ${{ parameters.dockerfilePath }} --target ${{ parameters.target }} -t ${{ parameters.target }}:${{ parameters.tag }} ${{ parameters.arguments }} .
      showWarnings: true
      errorActionPreference: default
      pwsh: true
      workingDirectory: ${{ parameters.workingDirectory }}
