parameters:
  - name: secureFile
    displayName: Name of the secure file to download
    type: string
    default: $(AWS_CREDENTIALS_SECURE_FILE_NAME)
  - name: awsProfile
    displayName:
    type: string
    default: $(AWS_PROFILE)

steps:
  - task: DownloadSecureFile@1
    displayName: Download AWS credentials
    inputs:
      secureFile: ${{ parameters.secureFile }}

  - task: PowerShell@2
    displayName: Configure AWS credentials
    inputs:
      targetType: inline
      script: |
        aws configure --profile $(AWS_PROFILE) 
      errorActionPreference: default
      showWarnings: true
      pwsh: true
    env:
      AWS_SHARED_CREDENTIALS_FILE: $(${{ parameters.secureFile }}.secureFilePath)