parameters:
  - name: secureFile
    displayName: Name of the secure file to download
    type: string
    default: $(AWS_CREDENTIALS_SECURE_FILE_NAME)

steps:
  - task: DownloadSecureFile@1
    displayName: Download AWS credentials
    inputs:
      secureFile: ${{ parameters.secureFile }}

  - task: PowerShell@2
    displayName: Set AWS credentials path
    inputs:
      targetType: inline
      script: |
        echo "##vso[task.setvariable variable=AWS_SHARED_CREDENTIALS_FILE]/home/vsts/work/_temp/${{ parameters.secureFile }}"
        Write-Host "AWS_SHARED_CREDENTIALS_FILE:$env:AWS_SHARED_CREDENTIALS_FILE"
      errorActionPreference: default
      showWarnings: true
      pwsh: true