parameters:
  - name: secureFile
    displayName: Name of the secure file to download
    type: string
    default: aws.credentials

steps:
  - task: DownloadSecureFile@1
    displayName: Download AWS credentials
    inputs:
      secureFile: ${{ parameters.secureFile }}

  - task: PowerShell@2
    displayName: Set AWS credentials path
    inputs:
      targetType: inline
      script: |
        Write-Host "##vso[task.setvariable variable=AWS_SHARED_CREDENTIALS_FILE]/home/vsts/work/_temp/${{ parameters.secureFile }}"
        Write-Host AWS_SHARED_CREDENTIALS_FILE:/home/vsts/work/_temp/${{ parameters.secureFile }}
      errorActionPreference: default
      showWarnings: true
      pwsh: true
    env:
      AWS_EC2_METADATA_DISABLED: true
  - task: PowerShell@2
    displayName: Set AWS account ID
    inputs:
      targetType: inline
      script: |
        $AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
        Write-Host "##vso[task.setvariable variable=AWS_ACCOUNT_ID]$AWS_ACCOUNT_ID"
        Write-Host AWS_ACCOUNT_ID:$AWS_ACCOUNT_ID
      errorActionPreference: default
      showWarnings: true
      pwsh: true
    env:
      AWS_EC2_METADATA_DISABLED: true
