variables:
  ENVIRONMENT: production
  TF_CLI_ARGS_INIT: -backend-config="dynamodb_table=expensely-terraform-lock-production-us-east-1" -backend-config="bucket=expensely-terraform-production-us-east-1"
