variables:
  CODEDEPLOY_BUCKET_NAME: expensely-code-deploy-production
  ENVIRONMENT: production
  TF_CLI_ARGS_INIT: -backend-config="dynamodb_table=expensely-terraform-lock-production-ap-southeast-2" -backend-config="bucket=expensely-terraform-production-ap-southeast-2"
  TEST_RESULTS_BUCKET_NAME: expensely-test-results-production
